(ns crb.csv.columns)




(def col-names ["Full name"
                "Industry"
                "Job title"
                "Sub Role"
                "Industry 2"
                "Emails"
                "Mobile"
                "Phone numbers"
                "Company Name"
                "Company Industry"
                "Company Website"
                "Company Size"
                "Company Founded"
                "Location"
                "Locality"
                "Metro"
                "Region"
                "Skills"
                "First Name"
                "Middle Initial"
                "Middle Name"
                "Last Name"
                "Birth Year"
                "Birth Date"
                "Gender"
                "LinkedIn Url"
                "LinkedIn Username"
                "Facebook Url"
                "Facebook Username"
                "Twitter Url"
                "Twitter Username"
                "Github Url"
                "Github Username"
                "Company Linkedin Url"
                "Company Facebook Url"
                "Company Twitter Url"
                "Company Location Name"
                "Company Location Locality"
                "Company Location Metro"
                "Company Location Region"
                "Company Location Geo"
                "Company Location Street Address"
                "Company Location Address Line 2"
                "Company Location Postal Code"
                "Company Location Country"
                "Company Location Continent"
                "Last Updated"
                "Start Date"
                "Job Summary"
                "Location Country"
                "Location Continent"
                "Street Address"
                "Address Line 2"
                "Postal Code"
                "Location Geo"
                "Last Updated"
                "Linkedin Connections"
                "Inferred Salary"
                "Years Experience"
                "Summary"
                "Countries"
                "Interests"])


